package com_gyroscope

// list import classes
import com.iotbpm.model.Devices;
import com.iotbpm.model.DeviceEvent;

// default dialect for the semantic code will be JAVA
dialect "java"

rule "Device Gyroscope Readings"
	when
        $event : DeviceEvent( $eventId : id, $accel_x : accel_x, $accel_y : accel_y, $accel_z : accel_z, $gyro_x : gyro_x, $gyro_y : gyro_y, $gyro_z : gyro_z, $magnet_x : magnet_x, $magnet_y : magnet_y, $magnet_z : magnet_z )
      	$device : Devices( $deviceId : id,  $eventId == id )
	then
		$device.setAction( $event.getEvent() ); 
		com.iotbpm.ui.MainWindow.getInstance().log($event.getName() + "  accel " + $accel_x + " " + $accel_y + " " + $accel_z + " " + "  gyro " + $gyro_x + " " + $gyro_y + " " + $gyro_z + " " + "  magnet " + $magnet_x + " " + $magnet_y + " " + $magnet_z );
		//modify( $device );
end

rule "Device Gyroscope Positive zBias"
	when
        $event : DeviceEvent( $eventId : id, $magnet_z : magnet_z, $magnet_z > 0 )
      	$device : Devices( $deviceId : id,  $eventId == id )
	then
		$device.setAction( $event.getEvent() ); 
		$device.setStatus( "Face Up" );
		//modify( $device );
end

rule "Device Gyroscope Negative zBias"
	when
        $event : DeviceEvent( $eventId : id, $magnet_z : magnet_z, $magnet_z < 0 )
      	$device : Devices( $deviceId : id,  $eventId == id )
	then
		$device.setAction( $event.getEvent() ); 
		$device.setStatus( "Face Down" );
		//modify( $device );
end

rule "Device Address Location"
	when
        $event : DeviceEvent( $eventId : id, $address : address, $address != "null" )
      	$device : Devices( $deviceId : id,  $eventId == id )
	then
		com.iotbpm.ui.MainWindow.getInstance().log($event.getName() + " location " + $address);
end

rule "Device is in Motion"
	when
        $event : DeviceEvent( $eventId : id, $gyro_x : gyro_x, $gyro_y : gyro_y, $gyro_z : gyro_z, gyro_x != 0, gyro_y != 0, gyro_z != 0 )
      	$device : Devices( $deviceId : id,  $eventId == id )
	then
		com.iotbpm.ui.MainWindow.getInstance().log("Device " + $device.getName() + " in Motion");
end

