package com.automation

// list import classes
import com.iotbpm.model.Devices;
import com.iotbpm.model.ServerEvent;
import com.iotbpm.model.StateList;

// default dialect for the semantic code will be MVEL
dialect "mvel"

rule "processID rule for device ID: 100555 - Arduino Dash Button"
	when
		$event : ServerEvent( $eventId : id, $eventId == "100555" )
	then
		com.iotbpm.model.StateList.getInstance().putState("processID", "com.DashButton");
end

rule "processID rule for device ID: 100666 - Door Open Sensor ESP01"
	when
		$event : ServerEvent( $eventId : id, $eventId == "100666" )
	then
		com.iotbpm.model.StateList.getInstance().putState("processID", "com.DoorOpenSensorESP01");
end

rule "Rules for device ID: 100666 - Door Open Sensor ESP01"
 	no-loop
    when
    	// event used to change update Door Open Sensor ESP01
		$event : ServerEvent( $eventId : id, $eventId == "100666" )
      	$device : Devices( $deviceId : id,  $eventId == id )
    then
		$device.status = "Sensor";
		$device.action = "Opened";
		com.iotbpm.ui.MainWindow.getInstance().log("Door Open Sensor " + $device.getName());
		modify( $device );
		update( $device );
end





/*
rule "No Trains Are Moving - Quite Rule"
	when
		accumulate ( $device : Devices( $deviceId : id, $device.status == "Move" ); $cnt : count(1) ; $cnt == 0 )
then
		com.iotbpm.ui.MainWindow.getInstance().log("<Quite> No Trains Are Moving.");
end

rule "One Train is Moving - Safe Rule"
	when
		accumulate ( $device : Devices( $deviceId : id, $device.status == "Move" ); $cnt : count(1); $cnt == 1 )
then
		com.iotbpm.ui.MainWindow.getInstance().log("<Safe> Only One Train is Moving.");
end

rule "More Than One Train is Moving - Slow Rule"
	when
		accumulate ( $device : Devices( $deviceId : id, $device.status == "Move" ); $cnt : count(1); $cnt > 1 )
then
		com.iotbpm.ui.MainWindow.getInstance().log("<Slow> More Than One Train is Moving.");
end

//declare rule to fire when Device in Motion
rule "Device in Motion Rule"
    when
        $event : ServerEvent( $eventId : id, $motion : motion, $motion == true )
      	$device : Devices( $deviceId : id,  $eventId == id )
    then
		com.iotbpm.ui.MainWindow.getInstance().log("<Device " + $device.getName() + " in Motion>");
end
*/