package com.device

// list import classes
import com.iotbpm.model.Devices;
import com.iotbpm.model.DeviceEvent;

// default dialect for the semantic code will be MVEL
dialect "mvel"

rule "GPS Device Distance"
	when
        $event : DeviceEvent( $eventId : id, $lat : lat, $lon : lon, $altitude : altitude, $distance : distance, $totalDistance : totalDistance )
      	$device : Devices( $deviceId : id,  $eventId == id )
	then
		$device.action = "GPS";
		$device.status = $event.getEvent();
		com.iotbpm.ui.MainWindow.getInstance().log($event.getName() + " GPS Distance:" + $distance + " Total:" + $totalDistance + " Altitude:" + $altitude);
		modify( $device )
end

//declare rule to fire when Device speed is over 60
rule "GPS Device Speed Alert"
	when
        $event : DeviceEvent( $eventId : id, $lat : lat, $lon : lon, $altitude : altitude, $speed : speed, $speed > "60" )
      	$device : Devices( $deviceId : id,  $eventId == id )
	then
		$device.action = "Alert";
		$device.status = $event.getEvent();
		com.iotbpm.ui.MainWindow.getInstance().log($event.getName() + " GPS Speed Alert lat:" + $lat + " lon:" + $lon + " speed:" + $speed);
		modify( $device )
end

rule "GPS Device Fix Information"
	when
        $event : DeviceEvent( $eventId : id, $serverTime : serverTime, $deviceTime : deviceTime, $fixTime : fixTime, $outdated : outdated, $valid : valid ) 
      	$device : Devices( $deviceId : id,  $eventId == id )
	then
		com.iotbpm.ui.MainWindow.getInstance().log($event.getName() + " GPS Fix on " + $deviceTime);
end

rule "GPS Device Address Location"
	when
        $event : DeviceEvent( $eventId : id, $address : address, $address != "null" )
      	$device : Devices( $deviceId : id,  $eventId == id )
	then
		com.iotbpm.ui.MainWindow.getInstance().log($event.getName() + " location " + $address);
end

rule "GPS Device Sent Text Message"
	when
        $event : DeviceEvent( $eventId : id, $textMessage : textMessage, $textMessage != null )
      	$device : Devices( $deviceId : id,  $eventId == id )
	then
		com.iotbpm.ui.MainWindow.getInstance().log($event.getName() + " Text Message: " + $textMessage);
end

rule "GPS Device Sent Alarm"
	when
        $event : DeviceEvent( $eventId : id, $alarm : alarm, $alarm != null )
      	$device : Devices( $deviceId : id,  $eventId == id )
	then
		com.iotbpm.ui.MainWindow.getInstance().log($event.getName() + " Sent Alarm: " + $alarm);
end

//declare rule to fire when Device in Motion
rule "GPS Device is in Motion"
    when
        $event : DeviceEvent( $eventId : id, $motion : motion, $motion == true )
      	$device : Devices( $deviceId : id,  $eventId == id )
    then
		com.iotbpm.ui.MainWindow.getInstance().log("GPS Device " + $device.getName() + " in Motion");
end
