package com_light

// list import classes
import com.iotbpm.model.Devices;
import com.iotbpm.model.DeviceEvent;

// default dialect for the semantic code will be JAVA
dialect "java"

rule "event=allEvents Rule"
    when
        $event : DeviceEvent( $eventId : id, event == "allEvents" )
      	$device : Devices( $deviceId : id,  $eventId == id )
    then
		$device.setAction( "allEvents" ); 
		$device.setStatus( "Light " + $event.getLight() );
		com.iotbpm.ui.MainWindow.getInstance().log("Rule event=allEvents: " + $event.getEvent() + " - " + $event.getName() + " - " + " Light Value: " + $event.getLight());
		//modify( $device );
end

rule "keypress1.0 Rule"
    when
        $event : DeviceEvent( $eventId : id, event == "keypress1.0" )
      	$device : Devices( $deviceId : id,  $eventId == id )
    then
		$device.setAction( "keypress1.0" ); 
		$device.setStatus( "Light " + $event.getLight() );
		com.iotbpm.ui.MainWindow.getInstance().log("Rule keypress1.0: " + $event.getEvent() + " - " + $event.getName() + " - " + " Light Value: " + $event.getLight());
		//modify( $device );
end

rule "keypress2.0 Rule"
    when
        $event : DeviceEvent( $eventId : id, event == "keypress2.0" )
      	$device : Devices( $deviceId : id,  $eventId == id )
    then
		$device.setAction( "keypress2.0" ); 
		$device.setStatus( "Light " + $event.getLight() );
		com.iotbpm.ui.MainWindow.getInstance().log("Rule keypress2.0: " + $event.getEvent() + " - " + $event.getName() + " - " + " Light Value: " + $event.getLight());
		//modify( $device );
end

rule "keypress4.0 reedRelay"
    when
        $event : DeviceEvent( $eventId : id, event == "keypress4.0")
      	$device : Devices( $deviceId : id,  $eventId == id )
    then
		$device.setAction( "reedRelay" ); 
		$device.setStatus( "Light " + $event.getLight() );
		com.iotbpm.ui.MainWindow.getInstance().log("Rule keypress4.0 reedRelay: " + $event.getEvent() + " - " + $event.getName() + " - " + " Light Value: " + $event.getLight());
		//modify( $device );
end

rule "keypress8.0 proximity"
    when
        $event : DeviceEvent( $eventId : id, event == "keypress8.0") 
      	$device : Devices( $deviceId : id,  $eventId == id )
    then
		$device.setAction( "proximity" ); 
		$device.setStatus( "Light " + $event.getLight() );
		com.iotbpm.ui.MainWindow.getInstance().log("Rule keypress8.0 proximity: " + $event.getEvent() + " - " + $event.getName() + " - " + " Light Value: " + $event.getLight());
		//modify( $device );
end

//declare any ruleflow-group rules to fire in the jBPM com.Light process
rule "Rule for device ID: 100111"
	ruleflow-group "Light Rule Flow"
	when
		$event : DeviceEvent( $eventId : id, $eventId == "100111" )
	then
		com.iotbpm.ui.MainWindow.getInstance().log("ruleflow-group device ID: 100111 " + $event.getName() + " - " + $event.getEvent());
end

rule "Rule for device ID: 100222"
	ruleflow-group "Light Rule Flow"
	when
		$event : DeviceEvent( $eventId : id, $eventId == "100222" )
	then
		com.iotbpm.ui.MainWindow.getInstance().log("ruleflow-group device ID: 100222 " + $event.getName() + " - " + $event.getEvent());
end
